version: '3.1'

services:
  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - consignment-service
  consignment-service:
    build: ./consignment-service
    ports:
      - "50051:50051"
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - vessel-service
  vessel-service:
    build: ./vessel-service
    ports:
      - "50052:50051"
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADRESS: ":50051"
      DB_HOST: "datastore:27017"
  datastore:
    image: mongo
    ports:
      - "27017:27017"