version: '3.1'

services:
  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - consignment-service
  consignment-service:
    build: ./consignment-service
    ports:
      - "50051:50051"
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - vessel-service
      - datastore
  vessel-service:
    build: ./vessel-service
    ports:
      - "50052:50051"
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_SERVER_ADRESS: ":50051"
      DB_HOST: "datastore:27017"
    depends_on:
      - datastore
  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"
  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database
  datastore:
    image: mongo
    ports:
      - "27017:27017"
  database:
    image: postgres
    ports:
      - 5432:5432